# 雲端部署專用設定
spring.cloud.gcp.sql.instance-connection-name=curry-491814:asia-east1:free-trial-first-project
spring.cloud.gcp.sql.database-name=curry
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

# 關閉 DDL 自動更新（雲端環境建議手動管理或設為 none/validate）
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1